### ISSUE TITLE
Date format issues with philog

### ISSUE THREAD

**Issue by ozancaglayan** [mjpost/bin#1]
Hi Matt,

I tried to use `philog` but the `date` command inside the logger is locale/settings dependent and the subsequent regexp used to parse it may or may not be adequate for the logged timestamp. There's an easy fix to force the same datetime format when logging but then this may break current users unless handling of it is introduced. 

My system's date output is: "Mon 30 Sep 15:15:00 BST 2019" while the parser assumes that it should be "Mon Sep 30" and it fails.

I may send a PR if you are interested.

**Comment by mjpost** [comment]
Very interested in a PR. I've had it on my TODO list to change this to some ISO format, and then make it backwards compatible. I'd suggest YYYY-DD-MM HH:MM:SS UTC. What do you think of that?

**Comment by ozancaglayan** [comment]
yes that makes sense, I think that even the timezone/UTC is unnecessary. I think I'll just use my own fork of this repository and start directly with new timestamps without needing backward-compatibility :) I can also send you a PR but not sure if I can come up with a perl-perfect solution for backward-compatibility since I am a perl n00b.

Other than that, initially I thought that this utility also allows running a command again and again (sth like `ph run 1`) in an easy way but it turned out that it just dumps the previous command history for a given folder, right?

**Comment by mjpost** [comment]
If you change it to do `YYYY-DD-MM HH:MM:SS` and submit a PR, I'll do backward compat.

I have long wanted to add something like "ph run 1". It's a great idea. But `ph` is already an alias, so you should just add a flag to `philog` (e.g., `philog -r 1`) and then create an alias (e.g., `pr`). I'd take that, too!

**Comment by mjpost** [comment]
I forgot that I already started on this. [Here's the branch](https://github.com/mjpost/bin/tree/philog_datefix). I'll finish this, and also add `pr`, and let you know when it's done.

**Comment by ozancaglayan** [comment]
Sorry, I couldn't find some time to deal with this. Thanks!
